# Generated by Django 4.1 on 2023-01-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.title')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
